### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by holtwick** [ekzhang/bore#110]
I made your great tool work on a https://github.com/NginxProxyManager/nginx-proxy-manager driven virtual server. Maybe you'd like to add some of the following to your project:

1. Copy or clone this repo to the server
2. Modify Dockerfile to run in server mode. Basically I changed the last line to `ENTRYPOINT ["./bore", "server", "--min-port=8080", "--max-port=8080"]`
3. Add a `docker-compose.yml` and build and start it like `docker compose up -d`

```yml
# docker-compose.yml

version: '3'

services:
  tunnel:
    build: .
    restart: unless-stopped
    ports:
      - '7835:7835'

networks:
  default:
    external: true
    name: proxy
```

The `networks` line are specific to the proxy.

The port is required to get the protocol working.

In the proxy I configured like this:

![20240301-203911-capture-holtwick@2x](https://github.com/ekzhang/bore/assets/49557/a471282d-2fdf-4480-9ad5-d4200fdb93b9)

Now with something like `bore local 8080 --to tunnel.example.com` I can fire it up on the client. HTTPS also works fine if configured in the Nginx Proxy Manager.
